export const GET_RECIPES = "GET_RECIPES";
export const GET_RECIPES_NAME = "GET_RECIPES_NAME";
export const FILTER_RECIPES_BY_TYPE = "FILTER_RECIPES_BY_TYPE";
export const ORDER_RECIPES = "ORDER_RECIPES"